const currencies = [
  {
    id: "USD",
    country_name: "US Dollar",
    code: "USD",
    currency: "US Dollar",
    symbol: "$",
    symbol_native: "$",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "US dollars",
  },
  {
    id: "CAD",
    country_name: "Canadian Dollar",
    code: "CAD",
    currency: "Canadian Dollar",
    symbol: "CA$",
    symbol_native: "$",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Canadian dollars",
  },
  {
    id: "EUR",
    country_name: "Euro",
    code: "EUR",
    currency: "Euro",
    symbol: "€",
    symbol_native: "€",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "euros",
  },
  {
    id: "AED",
    country_name: "United Arab Emirates Dirham",
    code: "AED",
    currency: "United Arab Emirates Dirham",
    symbol: "AED",
    symbol_native: "د.إ.‏",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "UAE dirhams",
  },
  {
    id: "AFN",
    country_name: "Afghan Afghani",
    code: "AFN",
    currency: "Afghan Afghani",
    symbol: "Af",
    symbol_native: "؋",
    decimal_digit: 0,
    rounding: 0,
    name_pural: "Afghan Afghanis",
  },
  {
    id: "ALL",
    country_name: "Albanian Lek",
    code: "ALL",
    currency: "Albanian Lek",
    symbol: "ALL",
    symbol_native: "Lek",
    decimal_digit: 0,
    rounding: 0,
    name_pural: "Albanian lekë",
  },
  {
    id: "AMD",
    country_name: "Armenian Dram",
    code: "AMD",
    currency: "Armenian Dram",
    symbol: "AMD",
    symbol_native: "դր.",
    decimal_digit: 0,
    rounding: 0,
    name_pural: "Armenian drams",
  },
  {
    id: "ARS",
    country_name: "Argentine Peso",
    code: "ARS",
    currency: "Argentine Peso",
    symbol: "AR$",
    symbol_native: "$",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Argentine pesos",
  },
  {
    id: "AUD",
    country_name: "Australian Dollar",
    code: "AUD",
    currency: "Australian Dollar",
    symbol: "AU$",
    symbol_native: "$",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Australian dollars",
  },
  {
    id: "AZN",
    country_name: "Azerbaijani Manat",
    code: "AZN",
    currency: "Azerbaijani Manat",
    symbol: "man.",
    symbol_native: "ман.",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Azerbaijani manats",
  },
  {
    id: "BAM",
    country_name: "Bosnia-Herzegovina Convertible Mark",
    code: "BAM",
    currency: "Bosnia-Herzegovina Convertible Mark",
    symbol: "KM",
    symbol_native: "KM",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Bosnia-Herzegovina convertible marks",
  },
  {
    id: "BDT",
    country_name: "Bangladeshi Taka",
    code: "BDT",
    currency: "Bangladeshi Taka",
    symbol: "Tk",
    symbol_native: "৳",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Bangladeshi takas",
  },
  {
    id: "BGN",
    country_name: "Bulgarian Lev",
    code: "BGN",
    currency: "Bulgarian Lev",
    symbol: "BGN",
    symbol_native: "лв.",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Bulgarian leva",
  },
  {
    id: "BHD",
    country_name: "Bahraini Dinar",
    code: "BHD",
    currency: "Bahraini Dinar",
    symbol: "BD",
    symbol_native: "د.ب.‏",
    decimal_digit: 3,
    rounding: 0,
    name_pural: "Bahraini dinars",
  },
  {
    id: "BIF",
    country_name: "Burundian Franc",
    code: "BIF",
    currency: "Burundian Franc",
    symbol: "FBu",
    symbol_native: "FBu",
    decimal_digit: 0,
    rounding: 0,
    name_pural: "Burundian francs",
  },
  {
    id: "BND",
    country_name: "Brunei Dollar",
    code: "BND",
    currency: "Brunei Dollar",
    symbol: "BN$",
    symbol_native: "$",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Brunei dollars",
  },
  {
    id: "BOB",
    country_name: "Bolivian Boliviano",
    code: "BOB",
    currency: "Bolivian Boliviano",
    symbol: "Bs",
    symbol_native: "Bs",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Bolivian bolivianos",
  },
  {
    id: "BRL",
    country_name: "Brazilian Real",
    code: "BRL",
    currency: "Brazilian Real",
    symbol: "R$",
    symbol_native: "R$",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Brazilian reals",
  },
  {
    id: "BWP",
    country_name: "Botswanan Pula",
    code: "BWP",
    currency: "Botswanan Pula",
    symbol: "BWP",
    symbol_native: "P",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Botswanan pulas",
  },
  {
    id: "BYN",
    country_name: "Belarusian Ruble",
    code: "BYN",
    currency: "Belarusian Ruble",
    symbol: "Br",
    symbol_native: "руб.",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Belarusian rubles",
  },
  {
    id: "BZD",
    country_name: "Belize Dollar",
    code: "BZD",
    currency: "Belize Dollar",
    symbol: "BZ$",
    symbol_native: "$",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Belize dollars",
  },
  {
    id: "CDF",
    country_name: "Congolese Franc",
    code: "CDF",
    currency: "Congolese Franc",
    symbol: "CDF",
    symbol_native: "FrCD",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Congolese francs",
  },
  {
    id: "CHF",
    country_name: "Swiss Franc",
    code: "CHF",
    currency: "Swiss Franc",
    symbol: "CHF",
    symbol_native: "CHF",
    decimal_digit: 2,
    rounding: 0.05,
    name_pural: "Swiss francs",
  },
  {
    id: "CLP",
    country_name: "Chilean Peso",
    code: "CLP",
    currency: "Chilean Peso",
    symbol: "CL$",
    symbol_native: "$",
    decimal_digit: 0,
    rounding: 0,
    name_pural: "Chilean pesos",
  },
  {
    id: "CNY",
    country_name: "Chinese Yuan",
    code: "CNY",
    currency: "Chinese Yuan",
    symbol: "CN¥",
    symbol_native: "CN¥",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Chinese yuan",
  },
  {
    id: "COP",
    country_name: "Colombian Peso",
    code: "COP",
    currency: "Colombian Peso",
    symbol: "CO$",
    symbol_native: "$",
    decimal_digit: 0,
    rounding: 0,
    name_pural: "Colombian pesos",
  },
  {
    id: "CRC",
    country_name: "Costa Rican Colón",
    code: "CRC",
    currency: "Costa Rican Colón",
    symbol: "₡",
    symbol_native: "₡",
    decimal_digit: 0,
    rounding: 0,
    name_pural: "Costa Rican colóns",
  },
  {
    id: "CVE",
    country_name: "Cape Verdean Escudo",
    code: "CVE",
    currency: "Cape Verdean Escudo",
    symbol: "CV$",
    symbol_native: "CV$",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Cape Verdean escudos",
  },
  {
    id: "CZK",
    country_name: "Czech Republic Koruna",
    code: "CZK",
    currency: "Czech Republic Koruna",
    symbol: "Kč",
    symbol_native: "Kč",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Czech Republic korunas",
  },
  {
    id: "DJF",
    country_name: "Djiboutian Franc",
    code: "DJF",
    currency: "Djiboutian Franc",
    symbol: "Fdj",
    symbol_native: "Fdj",
    decimal_digit: 0,
    rounding: 0,
    name_pural: "Djiboutian francs",
  },
  {
    id: "DKK",
    country_name: "Danish Krone",
    code: "DKK",
    currency: "Danish Krone",
    symbol: "Dkr",
    symbol_native: "kr",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Danish kroner",
  },
  {
    id: "DOP",
    country_name: "Dominican Peso",
    code: "DOP",
    currency: "Dominican Peso",
    symbol: "RD$",
    symbol_native: "RD$",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Dominican pesos",
  },
  {
    id: "DZD",
    country_name: "Algerian Dinar",
    code: "DZD",
    currency: "Algerian Dinar",
    symbol: "DA",
    symbol_native: "د.ج.‏",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Algerian dinars",
  },
  {
    id: "EEK",
    country_name: "Estonian Kroon",
    code: "EEK",
    currency: "Estonian Kroon",
    symbol: "Ekr",
    symbol_native: "kr",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Estonian kroons",
  },
  {
    id: "EGP",
    country_name: "Egyptian Pound",
    code: "EGP",
    currency: "Egyptian Pound",
    symbol: "EGP",
    symbol_native: "ج.م.‏",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Egyptian pounds",
  },
  {
    id: "ERN",
    country_name: "Eritrean Nakfa",
    code: "ERN",
    currency: "Eritrean Nakfa",
    symbol: "Nfk",
    symbol_native: "Nfk",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Eritrean nakfas",
  },
  {
    id: "ETB",
    country_name: "Ethiopian Birr",
    code: "ETB",
    currency: "Ethiopian Birr",
    symbol: "Br",
    symbol_native: "Br",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Ethiopian birrs",
  },
  {
    id: "GBP",
    country_name: "British Pound Sterling",
    code: "GBP",
    currency: "British Pound Sterling",
    symbol: "£",
    symbol_native: "£",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "British pounds sterling",
  },
  {
    id: "GEL",
    country_name: "Georgian Lari",
    code: "GEL",
    currency: "Georgian Lari",
    symbol: "GEL",
    symbol_native: "GEL",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Georgian laris",
  },
  {
    id: "GHS",
    country_name: "Ghanaian Cedi",
    code: "GHS",
    currency: "Ghanaian Cedi",
    symbol: "GH₵",
    symbol_native: "GH₵",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Ghanaian cedis",
  },
  {
    id: "GNF",
    country_name: "Guinean Franc",
    code: "GNF",
    currency: "Guinean Franc",
    symbol: "FG",
    symbol_native: "FG",
    decimal_digit: 0,
    rounding: 0,
    name_pural: "Guinean francs",
  },
  {
    id: "GTQ",
    country_name: "Guatemalan Quetzal",
    code: "GTQ",
    currency: "Guatemalan Quetzal",
    symbol: "GTQ",
    symbol_native: "Q",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Guatemalan quetzals",
  },
  {
    id: "HKD",
    country_name: "Hong Kong Dollar",
    code: "HKD",
    currency: "Hong Kong Dollar",
    symbol: "HK$",
    symbol_native: "$",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Hong Kong dollars",
  },
  {
    id: "HNL",
    country_name: "Honduran Lempira",
    code: "HNL",
    currency: "Honduran Lempira",
    symbol: "HNL",
    symbol_native: "L",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Honduran lempiras",
  },
  {
    id: "HRK",
    country_name: "Croatian Kuna",
    code: "HRK",
    currency: "Croatian Kuna",
    symbol: "kn",
    symbol_native: "kn",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Croatian kunas",
  },
  {
    id: "HUF",
    country_name: "Hungarian Forint",
    code: "HUF",
    currency: "Hungarian Forint",
    symbol: "Ft",
    symbol_native: "Ft",
    decimal_digit: 0,
    rounding: 0,
    name_pural: "Hungarian forints",
  },
  {
    id: "IDR",
    country_name: "Indonesian Rupiah",
    code: "IDR",
    currency: "Indonesian Rupiah",
    symbol: "Rp",
    symbol_native: "Rp",
    decimal_digit: 0,
    rounding: 0,
    name_pural: "Indonesian rupiahs",
  },
  {
    id: "ILS",
    country_name: "Israeli New Sheqel",
    code: "ILS",
    currency: "Israeli New Sheqel",
    symbol: "₪",
    symbol_native: "₪",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Israeli new sheqels",
  },
  {
    id: "INR",
    country_name: "Indian Rupee",
    code: "INR",
    currency: "Indian Rupee",
    symbol: "Rs",
    symbol_native: "টকা",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Indian rupees",
  },
  {
    id: "IQD",
    country_name: "Iraqi Dinar",
    code: "IQD",
    currency: "Iraqi Dinar",
    symbol: "IQD",
    symbol_native: "د.ع.‏",
    decimal_digit: 0,
    rounding: 0,
    name_pural: "Iraqi dinars",
  },
  {
    id: "IRR",
    country_name: "Iranian Rial",
    code: "IRR",
    currency: "Iranian Rial",
    symbol: "IRR",
    symbol_native: "﷼",
    decimal_digit: 0,
    rounding: 0,
    name_pural: "Iranian rials",
  },
  {
    id: "ISK",
    country_name: "Icelandic Króna",
    code: "ISK",
    currency: "Icelandic Króna",
    symbol: "Ikr",
    symbol_native: "kr",
    decimal_digit: 0,
    rounding: 0,
    name_pural: "Icelandic krónur",
  },
  {
    id: "JMD",
    country_name: "Jamaican Dollar",
    code: "JMD",
    currency: "Jamaican Dollar",
    symbol: "J$",
    symbol_native: "$",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Jamaican dollars",
  },
  {
    id: "JOD",
    country_name: "Jordanian Dinar",
    code: "JOD",
    currency: "Jordanian Dinar",
    symbol: "JD",
    symbol_native: "د.أ.‏",
    decimal_digit: 3,
    rounding: 0,
    name_pural: "Jordanian dinars",
  },
  {
    id: "JPY",
    country_name: "Japanese Yen",
    code: "JPY",
    currency: "Japanese Yen",
    symbol: "¥",
    symbol_native: "￥",
    decimal_digit: 0,
    rounding: 0,
    name_pural: "Japanese yen",
  },
  {
    id: "KES",
    country_name: "Kenyan Shilling",
    code: "KES",
    currency: "Kenyan Shilling",
    symbol: "Ksh",
    symbol_native: "Ksh",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Kenyan shillings",
  },
  {
    id: "KHR",
    country_name: "Cambodian Riel",
    code: "KHR",
    currency: "Cambodian Riel",
    symbol: "KHR",
    symbol_native: "៛",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Cambodian riels",
  },
  {
    id: "KMF",
    country_name: "Comorian Franc",
    code: "KMF",
    currency: "Comorian Franc",
    symbol: "CF",
    symbol_native: "FC",
    decimal_digit: 0,
    rounding: 0,
    name_pural: "Comorian francs",
  },
  {
    id: "KRW",
    country_name: "South Korean Won",
    code: "KRW",
    currency: "South Korean Won",
    symbol: "₩",
    symbol_native: "₩",
    decimal_digit: 0,
    rounding: 0,
    name_pural: "South Korean won",
  },
  {
    id: "KWD",
    country_name: "Kuwaiti Dinar",
    code: "KWD",
    currency: "Kuwaiti Dinar",
    symbol: "KD",
    symbol_native: "د.ك.‏",
    decimal_digit: 3,
    rounding: 0,
    name_pural: "Kuwaiti dinars",
  },
  {
    id: "KZT",
    country_name: "Kazakhstani Tenge",
    code: "KZT",
    currency: "Kazakhstani Tenge",
    symbol: "KZT",
    symbol_native: "тңг.",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Kazakhstani tenges",
  },
  {
    id: "LBP",
    country_name: "Lebanese Pound",
    code: "LBP",
    currency: "Lebanese Pound",
    symbol: "L.L.",
    symbol_native: "ل.ل.‏",
    decimal_digit: 0,
    rounding: 0,
    name_pural: "Lebanese pounds",
  },
  {
    id: "LKR",
    country_name: "Sri Lankan Rupee",
    code: "LKR",
    currency: "Sri Lankan Rupee",
    symbol: "SLRs",
    symbol_native: "SL Re",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Sri Lankan rupees",
  },
  {
    id: "LTL",
    country_name: "Lithuanian Litas",
    code: "LTL",
    currency: "Lithuanian Litas",
    symbol: "Lt",
    symbol_native: "Lt",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Lithuanian litai",
  },
  {
    id: "LVL",
    country_name: "Latvian Lats",
    code: "LVL",
    currency: "Latvian Lats",
    symbol: "Ls",
    symbol_native: "Ls",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Latvian lati",
  },
  {
    id: "LYD",
    country_name: "Libyan Dinar",
    code: "LYD",
    currency: "Libyan Dinar",
    symbol: "LD",
    symbol_native: "د.ل.‏",
    decimal_digit: 3,
    rounding: 0,
    name_pural: "Libyan dinars",
  },
  {
    id: "MAD",
    country_name: "Moroccan Dirham",
    code: "MAD",
    currency: "Moroccan Dirham",
    symbol: "MAD",
    symbol_native: "د.م.‏",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Moroccan dirhams",
  },
  {
    id: "MDL",
    country_name: "Moldovan Leu",
    code: "MDL",
    currency: "Moldovan Leu",
    symbol: "MDL",
    symbol_native: "MDL",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Moldovan lei",
  },
  {
    id: "MGA",
    country_name: "Malagasy Ariary",
    code: "MGA",
    currency: "Malagasy Ariary",
    symbol: "MGA",
    symbol_native: "MGA",
    decimal_digit: 0,
    rounding: 0,
    name_pural: "Malagasy Ariaries",
  },
  {
    id: "MKD",
    country_name: "Macedonian Denar",
    code: "MKD",
    currency: "Macedonian Denar",
    symbol: "MKD",
    symbol_native: "MKD",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Macedonian denari",
  },
  {
    id: "MMK",
    country_name: "Myanma Kyat",
    code: "MMK",
    currency: "Myanma Kyat",
    symbol: "MMK",
    symbol_native: "K",
    decimal_digit: 0,
    rounding: 0,
    name_pural: "Myanma kyats",
  },
  {
    id: "MOP",
    country_name: "Macanese Pataca",
    code: "MOP",
    currency: "Macanese Pataca",
    symbol: "MOP$",
    symbol_native: "MOP$",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Macanese patacas",
  },
  {
    id: "MUR",
    country_name: "Mauritian Rupee",
    code: "MUR",
    currency: "Mauritian Rupee",
    symbol: "MURs",
    symbol_native: "MURs",
    decimal_digit: 0,
    rounding: 0,
    name_pural: "Mauritian rupees",
  },
  {
    id: "MXN",
    country_name: "Mexican Peso",
    code: "MXN",
    currency: "Mexican Peso",
    symbol: "MX$",
    symbol_native: "$",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Mexican pesos",
  },
  {
    id: "MYR",
    country_name: "Malaysian Ringgit",
    code: "MYR",
    currency: "Malaysian Ringgit",
    symbol: "RM",
    symbol_native: "RM",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Malaysian ringgits",
  },
  {
    id: "MZN",
    country_name: "Mozambican Metical",
    code: "MZN",
    currency: "Mozambican Metical",
    symbol: "MTn",
    symbol_native: "MTn",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Mozambican meticals",
  },
  {
    id: "NAD",
    country_name: "Namibian Dollar",
    code: "NAD",
    currency: "Namibian Dollar",
    symbol: "N$",
    symbol_native: "N$",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Namibian dollars",
  },
  {
    id: "NGN",
    country_name: "Nigerian Naira",
    code: "NGN",
    currency: "Nigerian Naira",
    symbol: "₦",
    symbol_native: "₦",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Nigerian nairas",
  },
  {
    id: "NIO",
    country_name: "Nicaraguan Córdoba",
    code: "NIO",
    currency: "Nicaraguan Córdoba",
    symbol: "C$",
    symbol_native: "C$",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Nicaraguan córdobas",
  },
  {
    id: "NOK",
    country_name: "Norwegian Krone",
    code: "NOK",
    currency: "Norwegian Krone",
    symbol: "Nkr",
    symbol_native: "kr",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Norwegian kroner",
  },
  {
    id: "NPR",
    country_name: "Nepalese Rupee",
    code: "NPR",
    currency: "Nepalese Rupee",
    symbol: "NPRs",
    symbol_native: "नेरू",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Nepalese rupees",
  },
  {
    id: "NZD",
    country_name: "New Zealand Dollar",
    code: "NZD",
    currency: "New Zealand Dollar",
    symbol: "NZ$",
    symbol_native: "$",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "New Zealand dollars",
  },
  {
    id: "OMR",
    country_name: "Omani Rial",
    code: "OMR",
    currency: "Omani Rial",
    symbol: "OMR",
    symbol_native: "ر.ع.‏",
    decimal_digit: 3,
    rounding: 0,
    name_pural: "Omani rials",
  },
  {
    id: "PAB",
    country_name: "Panamanian Balboa",
    code: "PAB",
    currency: "Panamanian Balboa",
    symbol: "B/.",
    symbol_native: "B/.",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Panamanian balboas",
  },
  {
    id: "PEN",
    country_name: "Peruvian Nuevo Sol",
    code: "PEN",
    currency: "Peruvian Nuevo Sol",
    symbol: "S/.",
    symbol_native: "S/.",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Peruvian nuevos soles",
  },
  {
    id: "PHP",
    country_name: "Philippine Peso",
    code: "PHP",
    currency: "Philippine Peso",
    symbol: "₱",
    symbol_native: "₱",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Philippine pesos",
  },
  {
    id: "PKR",
    country_name: "Pakistani Rupee",
    code: "PKR",
    currency: "Pakistani Rupee",
    symbol: "PKRs",
    symbol_native: "₨",
    decimal_digit: 0,
    rounding: 0,
    name_pural: "Pakistani rupees",
  },
  {
    id: "PLN",
    country_name: "Polish Zloty",
    code: "PLN",
    currency: "Polish Zloty",
    symbol: "zł",
    symbol_native: "zł",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Polish zlotys",
  },
  {
    id: "PYG",
    country_name: "Paraguayan Guarani",
    code: "PYG",
    currency: "Paraguayan Guarani",
    symbol: "₲",
    symbol_native: "₲",
    decimal_digit: 0,
    rounding: 0,
    name_pural: "Paraguayan guaranis",
  },
  {
    id: "QAR",
    country_name: "Qatari Rial",
    code: "QAR",
    currency: "Qatari Rial",
    symbol: "QR",
    symbol_native: "ر.ق.‏",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Qatari rials",
  },
  {
    id: "RON",
    country_name: "Romanian Leu",
    code: "RON",
    currency: "Romanian Leu",
    symbol: "RON",
    symbol_native: "RON",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Romanian lei",
  },
  {
    id: "RSD",
    country_name: "Serbian Dinar",
    code: "RSD",
    currency: "Serbian Dinar",
    symbol: "din.",
    symbol_native: "дин.",
    decimal_digit: 0,
    rounding: 0,
    name_pural: "Serbian dinars",
  },
  {
    id: "RUB",
    country_name: "Russian Ruble",
    code: "RUB",
    currency: "Russian Ruble",
    symbol: "RUB",
    symbol_native: "₽.",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Russian rubles",
  },
  {
    id: "RWF",
    country_name: "Rwandan Franc",
    code: "RWF",
    currency: "Rwandan Franc",
    symbol: "RWF",
    symbol_native: "FR",
    decimal_digit: 0,
    rounding: 0,
    name_pural: "Rwandan francs",
  },
  {
    id: "SAR",
    country_name: "Saudi Riyal",
    code: "SAR",
    currency: "Saudi Riyal",
    symbol: "SR",
    symbol_native: "ر.س.‏",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Saudi riyals",
  },
  {
    id: "SDG",
    country_name: "Sudanese Pound",
    code: "SDG",
    currency: "Sudanese Pound",
    symbol: "SDG",
    symbol_native: "SDG",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Sudanese pounds",
  },
  {
    id: "SEK",
    country_name: "Swedish Krona",
    code: "SEK",
    currency: "Swedish Krona",
    symbol: "Skr",
    symbol_native: "kr",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Swedish kronor",
  },
  {
    id: "SGD",
    country_name: "Singapore Dollar",
    code: "SGD",
    currency: "Singapore Dollar",
    symbol: "S$",
    symbol_native: "$",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Singapore dollars",
  },
  {
    id: "SOS",
    country_name: "Somali Shilling",
    code: "SOS",
    currency: "Somali Shilling",
    symbol: "Ssh",
    symbol_native: "Ssh",
    decimal_digit: 0,
    rounding: 0,
    name_pural: "Somali shillings",
  },
  {
    id: "SYP",
    country_name: "Syrian Pound",
    code: "SYP",
    currency: "Syrian Pound",
    symbol: "SY£",
    symbol_native: "ل.س.‏",
    decimal_digit: 0,
    rounding: 0,
    name_pural: "Syrian pounds",
  },
  {
    id: "THB",
    country_name: "Thai Baht",
    code: "THB",
    currency: "Thai Baht",
    symbol: "฿",
    symbol_native: "฿",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Thai baht",
  },
  {
    id: "TND",
    country_name: "Tunisian Dinar",
    code: "TND",
    currency: "Tunisian Dinar",
    symbol: "DT",
    symbol_native: "د.ت.‏",
    decimal_digit: 3,
    rounding: 0,
    name_pural: "Tunisian dinars",
  },
  {
    id: "TOP",
    country_name: "Tongan Paʻanga",
    code: "TOP",
    currency: "Tongan Paʻanga",
    symbol: "T$",
    symbol_native: "T$",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Tongan paʻanga",
  },
  {
    id: "TRY",
    country_name: "Turkish Lira",
    code: "TRY",
    currency: "Turkish Lira",
    symbol: "TL",
    symbol_native: "TL",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Turkish Lira",
  },
  {
    id: "TTD",
    country_name: "Trinidad and Tobago Dollar",
    code: "TTD",
    currency: "Trinidad and Tobago Dollar",
    symbol: "TT$",
    symbol_native: "$",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Trinidad and Tobago dollars",
  },
  {
    id: "TWD",
    country_name: "New Taiwan Dollar",
    code: "TWD",
    currency: "New Taiwan Dollar",
    symbol: "NT$",
    symbol_native: "NT$",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "New Taiwan dollars",
  },
  {
    id: "TZS",
    country_name: "Tanzanian Shilling",
    code: "TZS",
    currency: "Tanzanian Shilling",
    symbol: "TSh",
    symbol_native: "TSh",
    decimal_digit: 0,
    rounding: 0,
    name_pural: "Tanzanian shillings",
  },
  {
    id: "UAH",
    country_name: "Ukrainian Hryvnia",
    code: "UAH",
    currency: "Ukrainian Hryvnia",
    symbol: "₴",
    symbol_native: "₴",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Ukrainian hryvnias",
  },
  {
    id: "UGX",
    country_name: "Ugandan Shilling",
    code: "UGX",
    currency: "Ugandan Shilling",
    symbol: "USh",
    symbol_native: "USh",
    decimal_digit: 0,
    rounding: 0,
    name_pural: "Ugandan shillings",
  },
  {
    id: "UYU",
    country_name: "Uruguayan Peso",
    code: "UYU",
    currency: "Uruguayan Peso",
    symbol: "$U",
    symbol_native: "$",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Uruguayan pesos",
  },
  {
    id: "UZS",
    country_name: "Uzbekistan Som",
    code: "UZS",
    currency: "Uzbekistan Som",
    symbol: "UZS",
    symbol_native: "UZS",
    decimal_digit: 0,
    rounding: 0,
    name_pural: "Uzbekistan som",
  },
  {
    id: "VEF",
    country_name: "Venezuelan Bolívar",
    code: "VEF",
    currency: "Venezuelan Bolívar",
    symbol: "Bs.F.",
    symbol_native: "Bs.F.",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "Venezuelan bolívars",
  },
  {
    id: "VND",
    country_name: "Vietnamese Dong",
    code: "VND",
    currency: "Vietnamese Dong",
    symbol: "₫",
    symbol_native: "₫",
    decimal_digit: 0,
    rounding: 0,
    name_pural: "Vietnamese dong",
  },
  {
    id: "XAF",
    country_name: "CFA Franc BEAC",
    code: "XAF",
    currency: "CFA Franc BEAC",
    symbol: "FCFA",
    symbol_native: "FCFA",
    decimal_digit: 0,
    rounding: 0,
    name_pural: "CFA francs BEAC",
  },
  {
    id: "XOF",
    country_name: "CFA Franc BCEAO",
    code: "XOF",
    currency: "CFA Franc BCEAO",
    symbol: "CFA",
    symbol_native: "CFA",
    decimal_digit: 0,
    rounding: 0,
    name_pural: "CFA francs BCEAO",
  },
  {
    id: "YER",
    country_name: "Yemeni Rial",
    code: "YER",
    currency: "Yemeni Rial",
    symbol: "YR",
    symbol_native: "ر.ي.‏",
    decimal_digit: 0,
    rounding: 0,
    name_pural: "Yemeni rials",
  },
  {
    id: "ZAR",
    country_name: "South African Rand",
    code: "ZAR",
    currency: "South African Rand",
    symbol: "R",
    symbol_native: "R",
    decimal_digit: 2,
    rounding: 0,
    name_pural: "South African rand",
  },
  {
    id: "ZMK",
    country_name: "Zambian Kwacha",
    code: "ZMK",
    currency: "Zambian Kwacha",
    symbol: "ZK",
    symbol_native: "ZK",
    decimal_digit: 0,
    rounding: 0,
    name_pural: "Zambian kwachas",
  },
  {
    id: "ZWL",
    country_name: "Zimbabwean Dollar",
    code: "ZWL",
    currency: "Zimbabwean Dollar",
    symbol: "ZWL$",
    symbol_native: "ZWL$",
    decimal_digit: 0,
    rounding: 0,
    name_pural: "Zimbabwean Dollar",
  },
];
